# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine
GAMEPROJECTFILE =/home/elias/Documents/GitHub/Matura_Unreal/Matura_Unreal.uproject

TARGETS = \
	Matura_Unreal-Linux-DebugGame  \
	Matura_Unreal-Linux-Shipping  \
	Matura_Unreal \
	Matura_UnrealEditor-Linux-DebugGame  \
	Matura_UnrealEditor-Linux-Shipping  \
	Matura_UnrealEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Matura_UnrealEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Matura_UnrealEditor-Linux-Debug


Matura_Unreal-Linux-DebugGame:
	 $(PROJECTBUILD) Matura_Unreal Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Matura_Unreal-Linux-Shipping:
	 $(PROJECTBUILD) Matura_Unreal Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Matura_Unreal:
	 $(PROJECTBUILD) Matura_Unreal Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

Matura_UnrealEditor-Linux-DebugGame:
	 $(PROJECTBUILD) Matura_UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Matura_UnrealEditor-Linux-Shipping:
	 $(PROJECTBUILD) Matura_UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Matura_UnrealEditor:
	 $(PROJECTBUILD) Matura_UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
